#' @noRd
#' @keywords internal
draw_key_area_fade <- function(data, params, size) {
  flipped    <- params$flipped_aes   %||% FALSE
  fill_color <- data$fill            %||%  "grey20"
  a_start    <- data$alpha           %||% 1
  a_end      <- params$alpha_fade_to %||% 0

  # Gradient runs from opaque (data boundary) to transparent (baseline).
  # Coordinates are bbox-relative npc: 0 = bottom/left, 1 = top/right.

  if (flipped) {
    x1 <- 1
    y1 <- 0.5
    x2 <- 0
    y2 <- 0.5
  } else {
    x1 <- 0.5
    y1 <- 1
    x2 <- 0.5
    y2 <- 0
  }

  grid::rectGrob(gp = grid::gpar(
    fill = grid::linearGradient(
      colours = c(
        ggplot2::alpha(fill_color, a_start),
        ggplot2::alpha(fill_color, a_end)
      ),
      x1 = x1,
      y1 = y1,
      x2 = x2,
      y2 = y2
    ),
    col = NA
  ))
}

#' @rdname geom_area_fade
#' @format NULL
#' @usage NULL
#' @export
GeomAreaFade <- ggplot2::ggproto(
  "GeomAreaFade",
  ggplot2::GeomArea,

  extra_params = c(
    ggplot2::GeomArea$extra_params,
    "alpha_fade_to"
  ),

  draw_key = draw_key_area_fade,

  # Validation in setup_params() so the constructor stays pure boilerplate
  # and can be generated by make_constructor().

  setup_params = function(self, data, params) {
    params <- ggplot2::ggproto_parent(ggplot2::GeomArea, self)$setup_params(data, params)
    if (!rlang::is_scalar_double(params$alpha_fade_to) ||
        !is.finite(params$alpha_fade_to) ||
        params$alpha_fade_to < 0 || params$alpha_fade_to > 1) {
      cli::cli_abort(c(
        "{.arg alpha_fade_to} must be a single finite number in {.code [0, 1]}.",
        "x" = "Got {.val {params$alpha_fade_to}} instead."
      ))
    }

    params

  },

  draw_group = function(self, data, panel_params, coord,
                        flipped_aes   = FALSE,
                        alpha_fade_to = 0,
                        outline.type  = "upper",
                        ...) {


    if (nrow(data) < 2) {
      cli::cli_warn(c(
        "!" = "{.fn geom_area_fade}: dropping group with fewer than 2 observations.",
        "i" = "Consider filtering single-observation groups before plotting."
      ))
      return(ggplot2::zeroGrob())
    }

    # Build gradient -------------------------------------------------------
    # ggplot2 >= 4.0.0 accepts a linearGradient object as the fill aesthetic
    # inside draw_group(). All polygon construction, coord_munch, flip_data,
    # and align_padding handling is delegated entirely to the parent — the only
    # thing we change is injecting our gradient in place of the flat fill.

    a_start <- data$alpha[1] %||% 1

    # Gradient direction: from opaque at the data boundary to transparent at
    # the baseline. Coordinates are bbox-relative npc.
    if (flipped_aes) {
      x1 <- 1; y1 <- 0.5; x2 <- 0; y2 <- 0.5
    } else {
      x1 <- 0.5; y1 <- 1; x2 <- 0.5; y2 <- 0
    }

    data$fill <- list(grid::linearGradient(
      colours = c(
        ggplot2::alpha(data$fill[1], a_start),
        ggplot2::alpha(data$fill[1], alpha_fade_to)
      ),
      x1 = x1, y1 = y1, x2 = x2, y2 = y2
    ))

    # alpha is now baked into the gradient stops; clear it so the parent
    # does not apply it a second time and darken / lighten the gradient.
    data$alpha <- NA

    # Delegate everything else to GeomArea: align_padding filtering,
    # flip_data normalisation, coord_munch, polygon + outline construction.
    ggplot2::ggproto_parent(ggplot2::GeomArea, self)$draw_group(
      data, panel_params, coord,
      flipped_aes  = flipped_aes,
      outline.type = outline.type,
      ...
    )
  }
)

#' @title Area with Fading Linear Gradient
#' @description
#' This geom behaves much like [geom_area()] but uses [grid::linearGradient()]
#' to create area plots where the fill colour fades from opaque to transparent.
#'
#' @aesthetics GeomAreaFade
#' @seealso [geom_area()] for fully opaque area charts
#' @inheritSection ggplot2::geom_area Orientation
#' @inheritParams ggplot2::geom_area
#' @param alpha_fade_to A single finite number between 0 and 1. The alpha value
#'   the gradient fades *to*. Defaults to 0 (fully transparent).
#' @param gradient_stop A single finite number between 0 and 1. The relative
#'   position along the gradient axis at which full transparency (`alpha_fade_to`)
#'   is first reached. The fill remains at alpha_fade_to from this point to
#'   the end of the gradient. Defaults to 1 (transparency reached at the very
#'   end, i.e. the standard two-stop linear gradient). Values less than 1
#'   produce a faster initial fade followed by a flat transparent tail.
#' @param outline.type Which edges of the area to draw an outline on. One of
#'   `"none"` (default), `"upper"`, `"lower"`, `"both"` (`"upper"` and `"lower"`),
#'   or `"full"` (closed polygon outline).
#' @export
#' @examples
#' library(ggplot2)
#' df <- data.frame(
#'   g = c("a", "a", "a", "b", "b", "b"),
#'   x = c(1, 3, 5, 2, 4, 6),
#'   y = c(2, 5, 1, 3, 6, 7)
#' )
#'
#' a <- ggplot(df, aes(x, y, fill = g)) +
#'   theme_minimal()
#'
#' # default behaviour
#' a + geom_area_fade()
#'
#' # change overall opacity
#' a + geom_area_fade(alpha = .5)
#'
#' # fade from 75% to 25% opacity
#' a + geom_area_fade(alpha = .75, alpha_fade_to = .25)
#'
#' # reverse direction: transparent at top, opaque at baseline
#' a + geom_area_fade(alpha = 0, alpha_fade_to = 1)
#'
#' # draw upper and lower outlines only (no left/right edges)
#' a + geom_area_fade(outline.type = "both")
#'
#' # closed outline (all four edges)
#' a + geom_area_fade(outline.type = "full")
#'
#' # horizontal orientation
#' a + geom_area_fade(orientation = "y")
#'
#' # disable stat alignment (useful when x values are already aligned)
#' a + geom_area_fade(aes(colour = g), outline.type = "full", stat = "identity")
#'
geom_area_fade <- ggplot2::make_constructor(
  GeomAreaFade,
  stat = "align",
  position = "stack"
  )
